### ISSUE TITLE
Kit Name for Item View

### ISSUE THREAD

**Issue by darceyw** [minigolf2000/winsome-website#36]
Golf, part of the changes Papp requested I make (per your suggestion) is to include the kit name next to the kit's dimensions. That column doesn't appear to be part of the item select. There is a join to the kits table (which has the name field) in set_components, but no select.

How do I get kits.name to also be included in the select so I can display it? I've gotten as far as creating a function to "pluck" name from set_components (set_components.pluck(:name). But that is giving me all the kit names for the children of the parent, for each component.

Next week I'll post my code changes, but for now, if you have a quick solution, that would be great.

![Kit Item](https://user-images.githubusercontent.com/16492766/134748785-7b69fb99-b958-4b15-8cda-accb4c0c4189.png)

**Comment by minigolf2000** [comment]
I pushed a change to master, so now you should be able to do 
- `item.kits` which should correctly grab an item's kits. 
```rb
$ Item.find_by(itemno: 94360).kits.pluck(:name)
=> ["Stool", "Table"]
```
- On the `kit` object I've added an `item` function since it looks like you'll want to grab each item's dimensions too
```rb
$ Item.find_by(itemno: 94360).kits[0].item.length
=> "17.93"
$ Item.find_by(itemno: 94360).kits[1].item.length
=> "33.8"
```

**Comment by darceyw** [comment]
Think I pretty much have it working, enough to show to Papp to see if that's what he wants.

But can you tell me how the kit items get sorted? I'm displaying the Name, and Dimensions. But sometimes they come up as Table/Stool, and others as Stool/Table. 

My code is currently on ubuntu_test (.184)

![image](https://user-images.githubusercontent.com/16492766/135114016-c9d1fc44-85be-44c8-a8d6-13c2e92901d0.png)

![image](https://user-images.githubusercontent.com/16492766/135114095-1cb4643d-1a04-4a5f-96f6-3096982f5dbc.png)

**Comment by minigolf2000** [comment]
The sorting will be random by default. You can do 
```rb
Item.find_by(itemno: item.itemno).kits.order(:name).each do |child|
```
to sort by name alphabetically

https://apidock.com/rails/ActiveRecord/QueryMethods/order

**Comment by darceyw** [comment]
Thank you! I had tried various attempts at that sort of thing (had looked at the API Doc), but couldn't figure out the correct way.

However, please see email Papp sent today (I included your email when I responded to him). He wants it sorted by "main" component. I don't know of anything we have which specifies a main component, even in WDS.

I will sort by name for now.
